services:
  - name: test-action
    host: test.d2723f-dev.svc
    tags: [ ns.nr-gh-action ]
    port: 80
    protocol: http
    retries: 0
    routes:
      - name: test-action-route
        tags: [ ns.nr-gh-action ]
        hosts:
          - test-action.api.gov.bc.ca
        paths:
          - /
        methods:
          - GET
          - OPTIONS
        strip_path: false
        https_redirect_status_code: 426
        path_handling: v0
        plugins:  
          - name: key-auth
            tags: [ ns.nr-gh-action ]
            protocols: [ http, https ]
            config:
              key_names: ["X-API-KEY"]
              run_on_preflight: true
              hide_credentials: true
              key_in_body: false
          - name: acl
            tags: [ ns.nr-gh-action ]
            config:
              hide_groups_header: true
              allow: [ "F87926EE" ]

